# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "fb2e56b0055fc93aee7ade7973a70a52"
name = "TrackFlow"
application_url = "https://trackflow-production-0d42.up.railway.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = ["app/uninstalled"]
  uri = "/webhooks"

[access_scopes]
scopes = "read_orders,write_orders"

[auth]
redirect_urls = [ "https://trackflow-production-0d42.up.railway.app/api/auth" ]

[pos]
embedded = false
